### ISSUE TITLE
Error on landing

### ISSUE THREAD

**Issue by mcNuggets1** [Malcolm-Q/LC-LateGameUpgrades#369] opened 2024-03-10 17:09 UTC
https://i.imgur.com/333OrKd.png

**Comment by WhiteSpike** [comment] 2024-03-10 21:06
Can't reproduce the issue on current released version. Need more details.

**Comment by mcNuggets1** [comment] 2024-03-10 23:10
018e2aa0-bd8d-9d49-4c04-f10473d09766 is a r2modman code for all the mods i use.
I use advanced company for landing speed edits afaik.

**Comment by mcNuggets1** [comment] 2024-03-11 20:24
Makes beehives have 0 value.

**Comment by WhiteSpike** [comment] 2024-04-14 14:21
Closing due to not being able to reproduce this issue on latest release and lack of comments saying they are also having the same issue.

If the issue persists, make another issue where you post the logs file of when this happens and what mods are being used when this happened.

**Closed by WhiteSpike** 2024-04-14 14:21 UTC
Labels: Info Needed
