### ISSUE TITLE
Bug Report: LC Better Save v1.5.0 fails to register LGU saves, causing purchased upgrades to reset.

### ISSUE THREAD

**Issue by FireGeneral** [Malcolm-Q/LC-LateGameUpgrades#38] opened 2023-12-16 09:40 UTC
Aftering buying the upgrades in orbit, I quit the game and reopen the game to find your mod have reset my upgrades.
Checking inside the save folder it now has LGU_2, LGU_3 in it.
Further testing only show more weird things which I don't know if intended or not, but I now have LGU_2 - LGU_9, each with different values stored inside. (I test this all alone btw)

Edit: Yep, after playing some rounds, I can confirm your mod fails to register what I've already bought. Everytime I close my game and re-opens it, all of my upgrades that I've already bought in previous sessions disappear. The only workaround for me is to rebuy every upgrades every time I start up the game.

**Comment by various2w** [comment] 2023-12-16 11:46
Same issue here, after buying the upgrades (specifically, Back Muscles 835, Running Shoes 1000) and quitting the server (while in orbit), it does not save the upgrades for some reason.
And the same as OP said, I also tested this alone and have to rebuy the upgrades I bought every time I start up my save file just so that I can get my upgrades back.

For additional information (not sure if it's needed but I'll say it anyway):
- This happened in both Online (solo) and LAN (solo)
- v2.6.1 of Lategame_Upgrades
- v45 of Lethal Company

**Comment by FireGeneral** [comment] 2023-12-16 11:49
> Same issue here, after buying the upgrades (specifically, Back Muscles 835, Running Shoes 1000) and quitting the server (while in orbit), it does not save the upgrades for some reason. And the same as OP said, I also tested this alone and have to rebuy the upgrades I bought every time I start up my save file just so that I can get my upgrades back.
> 
> For additional information (not sure if it's needed but I'll say it anyway):
> 
> * This happened in both Online (solo) and LAN (solo)
> * v2.6.1 of Lategame_Upgrades
> * v45 of Lethal Company

OMFG.... Would you so happen to use LC Better Save v1.5.0?

**Comment by FireGeneral** [comment] 2023-12-16 11:53
I found that the newest version of the LC Better Save (v1.5.0) never register any of the LGU saves, instead, it keeps on creating new ones and renaming the pre-existing ones to LGU_(Number+1).
Downgrading back to LC Better Save v1.4.0 fix the issue.

**Comment by various2w** [comment] 2023-12-16 11:55
Ohhhh, Actually yes, I do use LCBetterSaves, that somewhat explains the problem

**Comment by nikolateslax** [comment] 2023-12-18 01:48
Throwing my two cents in. I'm not using LCBetterSaves, but my saves also are not loading in previously purchased upgrades. I've included my save and r2modman profile.

[Solo Data.zip](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/13698675/Solo.Data.zip)

**Comment by nikolateslax** [comment] 2023-12-18 06:03
> Throwing my two cents in. I'm not using LCBetterSaves, but my saves also are not loading in previously purchased upgrades. I've included my save and r2modman profile.
> 
> [Solo Data.zip](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/13698675/Solo.Data.zip)

Update: It appears that this was caused by being in LAN mode, as once I switched to Online it works fine. Maybe just not loading from file because it never gets a SteamID in LAN mode

**Comment by FireGeneral** [comment] 2023-12-18 07:48
> > Throwing my two cents in. I'm not using LCBetterSaves, but my saves also are not loading in previously purchased upgrades. I've included my save and r2modman profile.
> > [Solo Data.zip](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/13698675/Solo.Data.zip)
> 
> Update: It appears that this was caused by being in LAN mode, as once I switched to Online it works fine. Maybe just not loading from file because it never gets a SteamID in LAN mode

Uh... I'm playing Online. I never play on LAN mode.

**Comment by WhiteSpike** [comment] 2023-12-22 18:53
Solved the issue and pulled a [pull request](https://github.com/paul-merkamp/LCBetterSaves/pull/8) on BetterSave's repository. If all goes well, the issue should be fixed when they accept it and release a new version.

**Closed** 2023-12-23 01:14 UTC
Labels: bug
