### ISSUE TITLE
Incompatibile with CustomTranslatorCharLimit

### ISSUE THREAD

**Issue by Noranecore** [Malcolm-Q/LC-LateGameUpgrades#366] opened 2024-03-06 10:32 UTC
CustomTranslatorCharLimit changes the speed that messages are displayed, allows special characters, and patches the terminal to allow more characters than terminal limit. Seems like none of it works with LGU even when you have the Fast Encryption upgrade disabled.

**Comment by WhiteSpike** [comment] 2024-03-06 13:39
For reference, the original IL code instruction block is:
```c#
IL_028b: ldloc.s V_12 // input message
IL_028d: callvirt System.Int32 System.String::get_Length() // Length of the message
IL_0292: ldc.i4.s 10 // Default limit when transmitting
IL_029b: call System.Int32 UnityEngine.Mathf::Min(System.Int32,System.Int32) // Minimum between last two inserted values
```
Which translates to the minimum between the length of the message inputted into the terminal and 10.

And this is how LGU patches the game's code to allow Fast Encryption's intended behaviour, where they take both the value 10 and the input message to know what the outputted limit should be when transmitting.
```c#
IL_028b: ldloc.s V_12 // input message
IL_028d: callvirt System.Int32 System.String::get_Length() // Length of the message
IL_0292: ldc.i4.s 10 // Default limit when transmitting
IL_0294: ldloc.s V_12 // input message
// Fast Encryption's logic function where they check if the upgrade is active to use the message's length instead of only 10 characters, output value is used for the minimum function
// If the upgrade is active, output length of the message
// Otherwise, output 10
IL_0296: call System.Int32 MoreShipUpgrades.UpgradeComponents.OneTimeUpgrades.FastEncryption::GetLimitOfCharactersTransmit(System.Int32,System.String) characters
IL_029b: call System.Int32 UnityEngine.Mathf::Min(System.Int32,System.Int32) // Minimum between last two inserted values
```

CustomTranslatorCharLimit's way of patching the same code is look for the Min function (last instruction in the code block) and replace the value "10" (third instruction in the code block) with their intended value from configuration.
Why does it do this? Because it assumes that no code instructions will be inserted between the min function call and the value 10.

So what's gonna happen is that turns the previous code block into this:
```c#
IL_028b: ldloc.s V_12 // input message
IL_028d: callvirt System.Int32 System.String::get_Length() // Length of the message
IL_0292: ldc.i4.s 10 // Default limit when transmitting
IL_0294: ldloc.s V_12 // input message
IL_0296: ldc.i4 CustomTranslatorCharLimit.MaxCharLengthConfigurationValue // Configurated value for maximum amount of characters allowed to transmit
IL_029b: call System.Int32 UnityEngine.Mathf::Min(System.Int32,System.Int32) // Minimum between last two inserted values
```

This is not valid IL code instruction structure so it will fail and will not allow CustomTranslatorCharLimit from being loaded.

One way for them to solve this is do the same thing to find the min function call and look for the last valid number that will be used for the second parameter of the min function (because the value "10" can be replaced with any other value before they patch or to a function call which returns another value of the same type)

Other way could be to replace the value "10" directly, though this would lead to other mods (such as LGU) to break when patching due to vanila code no longer being present and the mods cannot influence the load order of all other mods.

I'm open to suggestions to which I can change from LGU's side if possible and reasonable. Just don't think I can't do much in terms of changing other mod's source code. And sorry if this message is too extensive, just want to explain fully what's going on.

**Comment by Noranecore** [comment] 2024-03-11 02:32
Looks like the mod author is inactive unfortunately

**Comment by WhiteSpike** [comment] 2024-04-09 19:54
Closing as the other author seems to be inactive so we won't be able to fix anything which causes incompatibility issues between these two mods.
If they decide to come back and contact about this particular issue, I will reopen this.

**Closed by WhiteSpike** 2024-04-09 19:54 UTC
Labels: Incompatibility
