### ISSUE TITLE
Scrap Insurance Didn't Work

### ISSUE THREAD

**Issue by Narobic** [Malcolm-Q/LC-LateGameUpgrades#238] opened 2024-01-22 04:04 UTC
I paid 400 credits for the scrap insurance, my team died, and we lost everything

[LogOutput.log](https://github.com/Malcolm-Q/LC-LateGameUpgrades/files/14004548/LogOutput.log)

018d2f57-b684-550f-9c09-37f2f964493f thunderstore profile

**Comment by Malcolm-Q** [comment] 2024-01-22 05:11
At the moment the default behavior for scrap insurance is only to insure the next moon visit and that moon visit only. So if you do or don't die the insurance is consumed.

Was that the case or did you buy it -> land -> wipe and lose everything?

**Comment by Narobic** [comment] 2024-01-22 05:56
I bought it, landed, then lost everything. 

Only thing I could think of is that it's conflicting with advanced company

**Comment by WhiteSpike** [comment] 2024-01-30 01:31
If you can provide logs of when this happens (it can be in a test save with the same mods where you spawn a couple of scrap, trigger scrap insurance, land, die and then see the result), I can try looking at the cause of it.

**Comment by aegiswing** [comment] 2024-02-02 05:04
Yeah, AC is the only thing I can think that could be conflicting with it, since the Loot Saver perk is a chance it might be overlapping the 100% chance Scrap Insurance has, try disabling the Loot Saver perk in the lobby preset, maybe??

**Comment by WhiteSpike** [comment] 2024-02-05 17:27
According to [Advanced Company's issue page](https://github.com/FluffyFishGames/AdvancedCompany/issues/89), the issue between "Save Loot" and "Scrap Insurance" should be resolved in their next release. I will be closing this but if the issue persists, make another one with logs and mod list please. It would streamline the process.

**Closed by WhiteSpike** 2024-02-05 17:27 UTC
Labels: Info Needed
