### ISSUE TITLE
running shoes not working

### ISSUE THREAD

**Issue by ElettroGame04** [Malcolm-Q/LC-LateGameUpgrades#494] opened 2024-06-21 01:15 UTC
recently rthe running shoes upgrade stopped working, i buy it and it says it's loaded in chat, but the speed is still the same, i tried removing the last mods i had installed but i can't find what is causing this, is there some mod that is incompatible whit this upgrade? if there is at least i know what mod to remove if it's installed.

**Comment by WhiteSpike** [comment] 2024-06-23 11:59
Duplicate of #489

**Closed by WhiteSpike** 2024-06-23 11:59 UTC
