### ISSUE TITLE
Disabling LGU's Medkit prevents UsualScrap's Medkit from being purchased

### ISSUE THREAD

**Issue by IAMSTRANGLO** [Malcolm-Q/LC-LateGameUpgrades#514] opened 2024-07-13 22:07 UTC
Wanted to test the Medkit item from [UsualScrap](https://thunderstore.io/c/lethal-company/p/etherealemil/UsualScrap/) and found that upon disabling LGU's Medkit from the config, the Medkit from UsualScrap would be unavailable in the store as well. I assume it is due to them both being named "Medkit".

**Comment by WhiteSpike** [comment] 2024-07-18 08:47
I'm not sure entirely who's fault is this because the game by design can't tolerate same keywords for different things in the terminal (example of Rocket launcher from Lethal Things and Rocky tag from Lethal Level Loader). I would assume that when I tell LethalLib to remove the medkit item from the store, it will remove all keywords related to the medkit, including mine and the other mod's.

Sadly, I can only look at this after my break (which should end on 29th)

**Comment by IAMSTRANGLO** [comment] 2024-07-18 13:18
Good to know, thank you for your time and I hope you enjoy your break

**Comment by WhiteSpike** [comment] 2024-07-29 19:17
Fixed by renaming this mod's medkit item to "Old Medkit". This way, it shouldn't conflict with other medkit-related items.

Is there a better solution? Probably. But I am too tired to do that, lol.

**Closed** 2024-07-30 12:45 UTC
Labels: bug, Fixed but not live
